use anyhow::{anyhow, Result};
use ed25519_dalek::{Signature, VerifyingKey, Verifier};
use std::path::PathBuf;

use crate::ipc::*;
#[cfg(test)]
use chrono::Utc;

// ed25519 verifying key baked into the binary (CAT-2/CAT-5): trust rides on this key's
// signature over the catalog bytes, never on the host that served them. Generated by the
// `catsign` tool (`cargo run --bin catsign -- pubkey`); re-run after rotating the seed.
const BAKED_PUBKEY: [u8; 32] = [
    0x7d, 0x3a, 0xed, 0x55, 0x95, 0x87, 0xa7, 0x24,
    0xa1, 0x5d, 0x45, 0xd2, 0xf9, 0xa1, 0x1a, 0xdd,
    0xba, 0x08, 0x74, 0xb4, 0xae, 0x0a, 0x38, 0xce,
    0x47, 0xbf, 0x53, 0x7f, 0xec, 0x67, 0x58, 0x61,
];

fn baked_key() -> VerifyingKey {
    VerifyingKey::from_bytes(&BAKED_PUBKEY).expect("valid pubkey")
}

pub fn catalog_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".kayon")
        .join("catalog")
}

/// Directory containing bundled resources (catalog + frontend dist).
/// Resolves via KAYON_ROOT env override, else the crate manifest dir baked at
/// build time (the src-tauri crate root), so it works regardless of CWD.
pub fn crate_root() -> PathBuf {
    if let Ok(root) = std::env::var("KAYON_ROOT") {
        return PathBuf::from(root);
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn bundled_catalog_path() -> PathBuf {
    crate_root().join("catalog").join("catalog.json")
}

fn bundled_sig_path() -> PathBuf {
    crate_root().join("catalog").join("catalog.json.sig")
}

pub fn load_bundled_catalog() -> Result<Catalog> {
    let path = bundled_catalog_path();
    if !path.exists() {
        return Err(anyhow!("bundled catalog not found at {}", path.display()));
    }
    let data = std::fs::read_to_string(&path)?;
    let mut catalog: Catalog = serde_json::from_str(&data)?;
    catalog.verified_signature = None;

    let sig_path = bundled_sig_path();
    if sig_path.exists() {
        let sig_bytes = std::fs::read(&sig_path)?;
        let json_bytes = std::fs::read(&path)?;
        let sig = Signature::from_slice(&sig_bytes).ok();
        if let Some(sig) = sig {
            if baked_key().verify(&json_bytes, &sig).is_ok() {
                catalog.verified_signature = Some("verified".to_string());
            }
        }
    }

    Ok(catalog)
}

pub fn load_local_catalog() -> Option<Catalog> {
    let dir = catalog_dir();
    let path = dir.join("catalog.json");
    if !path.exists() {
        return None;
    }
    let data = std::fs::read_to_string(&path).ok()?;
    let catalog: Catalog = serde_json::from_str(&data).ok()?;
    Some(catalog)
}

pub fn save_local_catalog(catalog: &Catalog) -> Result<()> {
    let dir = catalog_dir();
    std::fs::create_dir_all(&dir)?;
    let path = dir.join("catalog.json");
    let data = serde_json::to_string_pretty(catalog)?;
    std::fs::write(&path, data)?;
    Ok(())
}

pub fn get_active_catalog() -> Result<Catalog> {
    if let Some(local) = load_local_catalog() {
        return Ok(local);
    }
    load_bundled_catalog()
}

pub async fn fetch_remote_catalog() -> Result<Catalog> {
    let base_url = "https://raw.githubusercontent.com/thelabs-id/kayon/main/catalog";
    let json_url = format!("{}/catalog.json", base_url);
    let sig_url = format!("{}/catalog.json.sig", base_url);

    let client = reqwest::Client::new();
    let json_resp = client.get(&json_url).send().await?;
    let json_bytes = json_resp.bytes().await?.to_vec();

    let sig_resp = client.get(&sig_url).send().await?;
    let sig_bytes = sig_resp.bytes().await?.to_vec();

    let sig = Signature::from_slice(&sig_bytes)
        .map_err(|e| anyhow!("invalid signature: {}", e))?;
    baked_key().verify(&json_bytes, &sig)
        .map_err(|_| anyhow!("signature verification failed"))?;

    let mut catalog: Catalog = serde_json::from_slice(&json_bytes)?;
    catalog.verified_signature = Some("verified".to_string());

    Ok(catalog)
}

pub fn maybe_update_catalog(local: &Catalog, remote: &Catalog) -> bool {
    remote.revision > local.revision
}

pub fn generate_signing_keypair() -> (ed25519_dalek::SigningKey, ed25519_dalek::VerifyingKey) {
    use rand::rngs::OsRng;
    let signing_key = ed25519_dalek::SigningKey::generate(&mut OsRng);
    let verifying_key = signing_key.verifying_key();
    (signing_key, verifying_key)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_catalog_signature_verifies() {
        let json = std::fs::read(bundled_catalog_path()).expect("catalog.json present");
        let sig_bytes = std::fs::read(bundled_sig_path()).expect("catalog.json.sig present");
        let sig = Signature::from_slice(&sig_bytes).expect("valid signature bytes");
        // The baked-in verifying key must accept the bundled catalog (CAT-5).
        assert!(baked_key().verify(&json, &sig).is_ok(), "genuine catalog must verify");
    }

    #[test]
    fn tampered_catalog_is_rejected() {
        let mut json = std::fs::read(bundled_catalog_path()).expect("catalog.json present");
        let sig_bytes = std::fs::read(bundled_sig_path()).expect("catalog.json.sig present");
        let sig = Signature::from_slice(&sig_bytes).expect("valid signature bytes");
        // Flip one byte: verification must fail — trust rides on the signature, not the host.
        json.push(b'!');
        assert!(baked_key().verify(&json, &sig).is_err(), "tampered catalog must be rejected");
    }

    #[test]
    fn newer_revision_supersedes() {
        let a = Catalog { schema_version: 1, revision: 1, generated_at: Utc::now(), entries: vec![], source: "".into(), verified_signature: None };
        let b = Catalog { revision: 2, ..a.clone() };
        assert!(maybe_update_catalog(&a, &b));
        assert!(!maybe_update_catalog(&b, &a));
    }
}
