use anyhow::{anyhow, Result};
use ed25519_dalek::{Signature, VerifyingKey, Verifier};
use std::path::PathBuf;

use crate::ipc::*;
#[cfg(test)]
use chrono::Utc;

// ed25519 verifying key baked into the binary (CAT-2/CAT-5): trust rides on this key's
// signature over the catalog bytes, never on the host that served them. Generated by the
// `catsign` tool (`cargo run --bin catsign -- pubkey`); re-run after rotating the seed.
const BAKED_PUBKEY: [u8; 32] = [
    0xee, 0x01, 0x2e, 0x3e, 0xef, 0x36, 0x8a, 0x8e,
    0x93, 0x8b, 0x6f, 0x8d, 0x77, 0x68, 0x9c, 0x4b,
    0x66, 0x10, 0xfd, 0x4d, 0x21, 0x93, 0x13, 0x8f,
    0xa6, 0x14, 0xa2, 0x9a, 0xff, 0xb0, 0x8c, 0x0c,
];

fn baked_key() -> VerifyingKey {
    VerifyingKey::from_bytes(&BAKED_PUBKEY).expect("valid pubkey")
}

pub fn catalog_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".kayon")
        .join("catalog")
}

/// Directory containing bundled resources (catalog + frontend dist).
/// Resolves via KAYON_ROOT env override, else the crate manifest dir baked at
/// build time (the src-tauri crate root), so it works regardless of CWD.
pub fn crate_root() -> PathBuf {
    if let Ok(root) = std::env::var("KAYON_ROOT") {
        return PathBuf::from(root);
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}


// The bundled catalog + detached signature are embedded in the binary at build time. Embedding
// (rather than reading from disk) makes them tamper-evident — altering them requires modifying the
// signed binary — and removes any dependency on the working directory. Re-sign (`catsign sign`)
// before building whenever catalog.json changes so these stay consistent.
const BUNDLED_CATALOG_JSON: &[u8] = include_bytes!("../../catalog/catalog.json");
const BUNDLED_CATALOG_SIG: &[u8] = include_bytes!("../../catalog/catalog.json.sig");

/// Load the bundled catalog, failing closed if its embedded signature does not verify against the
/// baked-in key (CAT-5). The app never trusts an unsigned/tampered catalog's origins or checksums.
pub fn load_bundled_catalog() -> Result<Catalog> {
    let sig = Signature::from_slice(BUNDLED_CATALOG_SIG)
        .map_err(|e| anyhow!("bundled catalog signature malformed: {}", e))?;
    baked_key().verify(BUNDLED_CATALOG_JSON, &sig)
        .map_err(|_| anyhow!("bundled catalog signature verification failed — refusing to load"))?;
    let mut catalog: Catalog = serde_json::from_slice(BUNDLED_CATALOG_JSON)?;
    catalog.verified_signature = Some("verified".to_string());
    Ok(catalog)
}

/// Load the cached remote catalog ONLY if its detached signature verifies against the baked-in
/// key (CAT-5). A tampered or unsigned cache is ignored so it can never be preferred over the
/// bundled signed catalog — trust rides on the signature, never on a file being present.
pub fn load_local_catalog() -> Option<Catalog> {
    let dir = catalog_dir();
    let json_path = dir.join("catalog.json");
    let sig_path = dir.join("catalog.json.sig");
    if !json_path.exists() || !sig_path.exists() {
        return None;
    }
    let json_bytes = std::fs::read(&json_path).ok()?;
    let sig_bytes = std::fs::read(&sig_path).ok()?;
    let sig = Signature::from_slice(&sig_bytes).ok()?;
    if baked_key().verify(&json_bytes, &sig).is_err() {
        log::warn!("cached catalog signature invalid — ignoring cache, using bundled");
        return None;
    }
    let mut catalog: Catalog = serde_json::from_slice(&json_bytes).ok()?;
    catalog.verified_signature = Some("verified".to_string());
    Some(catalog)
}

/// Persist the EXACT signed bytes + detached signature (not a re-serialization, which would break
/// verification). Only ever called with bytes that already verified against the baked key.
pub fn save_local_catalog_raw(json_bytes: &[u8], sig_bytes: &[u8]) -> Result<()> {
    let dir = catalog_dir();
    std::fs::create_dir_all(&dir)?;
    std::fs::write(dir.join("catalog.json"), json_bytes)?;
    std::fs::write(dir.join("catalog.json.sig"), sig_bytes)?;
    Ok(())
}

pub fn get_active_catalog() -> Result<Catalog> {
    // Prefer whichever verified catalog has the higher revision. A newer bundled catalog from a
    // fresh install must win over an older signature-verified cache, and vice-versa (CAT-5).
    let cached = load_local_catalog();
    match (cached, load_bundled_catalog()) {
        (Some(local), Ok(bundled)) => {
            Ok(if local.revision >= bundled.revision { local } else { bundled })
        }
        (Some(local), Err(_)) => Ok(local),
        (None, bundled) => bundled,
    }
}

/// Fetch + verify the remote catalog. Returns the parsed catalog plus the raw signed bytes and
/// signature so the caller can atomically cache the exact verified bytes. Every outbound GET is
/// logged at egress (PRIV-5). Signature is checked before the bytes are trusted (CAT-2/CAT-5).
pub async fn fetch_remote_catalog(
    db: &std::sync::Arc<crate::db::Database>,
) -> Result<(Catalog, Vec<u8>, Vec<u8>)> {
    // Points at where the signed catalog actually lives in the repo. Trust rides on the signature
    // (CAT-5), so the host need not be trusted — this is just the fetch location.
    let base_url = "https://raw.githubusercontent.com/thelabs-id/kayon/main/src-tauri/catalog";
    let json_url = format!("{}/catalog.json", base_url);
    let sig_url = format!("{}/catalog.json.sig", base_url);

    let client = reqwest::Client::new();

    let json_resp = client.get(&json_url).send().await?;
    let json_status = json_resp.status().as_u16();
    let json_bytes = json_resp.bytes().await?.to_vec();
    crate::telemetry::log_network_request_full(
        db, "GET", &json_url, "catalog", 0, json_bytes.len() as u64, Some(json_status), None,
    );

    let sig_resp = client.get(&sig_url).send().await?;
    let sig_status = sig_resp.status().as_u16();
    let sig_bytes = sig_resp.bytes().await?.to_vec();
    crate::telemetry::log_network_request_full(
        db, "GET", &sig_url, "catalog", 0, sig_bytes.len() as u64, Some(sig_status), None,
    );

    let sig = Signature::from_slice(&sig_bytes)
        .map_err(|e| anyhow!("invalid signature: {}", e))?;
    baked_key().verify(&json_bytes, &sig)
        .map_err(|_| anyhow!("signature verification failed"))?;

    let mut catalog: Catalog = serde_json::from_slice(&json_bytes)?;
    if catalog.schema_version != SUPPORTED_SCHEMA_VERSION {
        return Err(anyhow!(
            "remote catalog schemaVersion {} unsupported (this build understands {}) — not adopting",
            catalog.schema_version, SUPPORTED_SCHEMA_VERSION
        ));
    }
    catalog.verified_signature = Some("verified".to_string());

    Ok((catalog, json_bytes, sig_bytes))
}

/// The catalog schema version this build understands. A remote manifest with a different
/// schemaVersion is rejected (CAT-5) — a future v2 that still deserializes could misinterpret
/// download/checksum/runtime fields, so we never adopt it as if it were v1.
pub const SUPPORTED_SCHEMA_VERSION: u32 = 1;

pub fn maybe_update_catalog(local: &Catalog, remote: &Catalog) -> bool {
    remote.schema_version == SUPPORTED_SCHEMA_VERSION && remote.revision > local.revision
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_catalog_loads_and_is_verified() {
        // The embedded catalog must verify against the baked key and load fail-closed (CAT-5).
        let c = load_bundled_catalog().expect("bundled catalog must verify and load");
        assert_eq!(c.verified_signature.as_deref(), Some("verified"));
        assert!(!c.entries.is_empty());
    }

    #[test]
    fn tampered_catalog_is_rejected() {
        let mut json = BUNDLED_CATALOG_JSON.to_vec();
        let sig = Signature::from_slice(BUNDLED_CATALOG_SIG).expect("valid signature bytes");
        // Flip one byte: verification must fail — trust rides on the signature, not the host.
        json.push(b'!');
        assert!(baked_key().verify(&json, &sig).is_err(), "tampered catalog must be rejected");
    }

    #[test]
    fn newer_revision_supersedes() {
        let a = Catalog { schema_version: 1, revision: 1, generated_at: Utc::now(), entries: vec![], source: "".into(), verified_signature: None };
        let b = Catalog { revision: 2, ..a.clone() };
        assert!(maybe_update_catalog(&a, &b));
        assert!(!maybe_update_catalog(&b, &a));
    }
}
