use anyhow::{anyhow, Result};
use ed25519_dalek::{Signature, VerifyingKey, Verifier};
use std::path::PathBuf;

use crate::ipc::*;

// ed25519 verifying key baked into the binary (CAT-2/CAT-5): trust rides on this key's
// signature over the catalog bytes, never on the host that served them. Generated by the
// `catsign` tool (`cargo run --bin catsign -- pubkey`); re-run after rotating the seed.
const BAKED_PUBKEY: [u8; 32] = [
    0xee, 0x01, 0x2e, 0x3e, 0xef, 0x36, 0x8a, 0x8e,
    0x93, 0x8b, 0x6f, 0x8d, 0x77, 0x68, 0x9c, 0x4b,
    0x66, 0x10, 0xfd, 0x4d, 0x21, 0x93, 0x13, 0x8f,
    0xa6, 0x14, 0xa2, 0x9a, 0xff, 0xb0, 0x8c, 0x0c,
];

fn baked_key() -> VerifyingKey {
    VerifyingKey::from_bytes(&BAKED_PUBKEY).expect("valid pubkey")
}

pub fn catalog_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".kayon")
        .join("catalog")
}

/// Directory containing bundled resources (catalog + frontend dist).
/// Resolves via KAYON_ROOT env override, else the crate manifest dir baked at
/// build time (the src-tauri crate root), so it works regardless of CWD.
pub fn crate_root() -> PathBuf {
    if let Ok(root) = std::env::var("KAYON_ROOT") {
        return PathBuf::from(root);
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}


// The bundled catalog + detached signature are embedded in the binary at build time. Embedding
// (rather than reading from disk) makes them tamper-evident — altering them requires modifying the
// signed binary — and removes any dependency on the working directory. Re-sign (`catsign sign`)
// before building whenever catalog.json changes so these stay consistent.
const BUNDLED_CATALOG_JSON: &[u8] = include_bytes!("../../catalog/catalog.json");
const BUNDLED_CATALOG_SIG: &[u8] = include_bytes!("../../catalog/catalog.json.sig");

/// Load the bundled catalog, failing closed if its embedded signature does not verify against the
/// baked-in key (CAT-5). The app never trusts an unsigned/tampered catalog's origins or checksums.
pub fn load_bundled_catalog() -> Result<Catalog> {
    let sig = Signature::from_slice(BUNDLED_CATALOG_SIG)
        .map_err(|e| anyhow!("bundled catalog signature malformed: {}", e))?;
    baked_key().verify(BUNDLED_CATALOG_JSON, &sig)
        .map_err(|_| anyhow!("bundled catalog signature verification failed — refusing to load"))?;
    let mut catalog: Catalog = serde_json::from_slice(BUNDLED_CATALOG_JSON)?;
    catalog.verified_signature = Some("verified".to_string());
    Ok(catalog)
}

/// Path of the cached runtime-discovered catalog (CAT-7). Written by Kayon itself from Hugging Face
/// data, so it is not detached-signed — its integrity rests on the per-quant checksum pins that the
/// download gate (DL-3) enforces, not on a signature.
fn discovered_catalog_path() -> PathBuf {
    catalog_dir().join("discovered.json")
}

/// Load the cached runtime-discovered catalog, if present and of a schema this build understands.
/// This is Kayon's own cache of a prior HF discovery, reused offline and as the arch cache for the
/// next discovery — not something an external host signs, so there is no signature to verify.
pub fn load_discovered_catalog() -> Option<Catalog> {
    let json_bytes = std::fs::read(discovered_catalog_path()).ok()?;
    let catalog: Catalog = serde_json::from_slice(&json_bytes).ok()?;
    if catalog.schema_version != SUPPORTED_SCHEMA_VERSION {
        log::warn!("discovered-catalog cache schemaVersion unsupported — ignoring, using bundled");
        return None;
    }
    Some(catalog)
}

/// Persist a freshly discovered catalog to the per-user cache (CAT-7). Every entry is already
/// checksum-pinned from HF; the cache is plain JSON that only Kayon writes and reads.
pub fn save_discovered_catalog(catalog: &Catalog) -> Result<()> {
    let dir = catalog_dir();
    std::fs::create_dir_all(&dir)?;
    std::fs::write(discovered_catalog_path(), serde_json::to_vec_pretty(catalog)?)?;
    Ok(())
}

/// Persist the EXACT signed bytes + detached signature (not a re-serialization, which would break
/// verification). Only ever called with bytes that already verified against the baked key.
pub fn get_active_catalog() -> Result<Catalog> {
    // Prefer the runtime-discovered catalog (CAT-7): it is the freshest view of Hugging Face, every
    // entry is checksum-pinned, and it supersedes the bundled seed. The bundled *signed* catalog
    // (CAT-5) is the offline anchor used until the first discovery lands, or if discovery is off.
    // Guard on revision so a stale cache can never shadow a newer bundled build.
    match (load_discovered_catalog(), load_bundled_catalog()) {
        (Some(disc), Ok(bundled)) => Ok(if disc.revision >= bundled.revision { disc } else { bundled }),
        (Some(disc), Err(_)) => Ok(disc),
        (None, bundled) => bundled,
    }
}

/// An empty catalog of the supported schema — used as a discovery seed when no catalog can be
/// loaded (the arch cache is then simply empty, so every model's header is fetched fresh).
pub fn empty_catalog() -> Catalog {
    Catalog {
        schema_version: SUPPORTED_SCHEMA_VERSION,
        revision: 0,
        generated_at: chrono::Utc::now(),
        entries: vec![],
        source: "empty".to_string(),
        verified_signature: None,
    }
}

/// The catalog schema version this build understands. A catalog with a different schemaVersion is
/// rejected — a future v2 that still deserializes could misinterpret download/checksum/runtime
/// fields, so we never adopt it as if it were v1.
pub const SUPPORTED_SCHEMA_VERSION: u32 = 1;

/// Whether a freshly discovered catalog should replace the current one: same schema, newer revision.
pub fn maybe_update_catalog(local: &Catalog, remote: &Catalog) -> bool {
    remote.schema_version == SUPPORTED_SCHEMA_VERSION && remote.revision > local.revision
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_catalog_loads_and_is_verified() {
        // The embedded catalog must verify against the baked key and load fail-closed (CAT-5).
        let c = load_bundled_catalog().expect("bundled catalog must verify and load");
        assert_eq!(c.verified_signature.as_deref(), Some("verified"));
        assert!(!c.entries.is_empty());
    }

    #[test]
    fn tampered_catalog_is_rejected() {
        let mut json = BUNDLED_CATALOG_JSON.to_vec();
        let sig = Signature::from_slice(BUNDLED_CATALOG_SIG).expect("valid signature bytes");
        // Flip one byte: verification must fail — trust rides on the signature, not the host.
        json.push(b'!');
        assert!(baked_key().verify(&json, &sig).is_err(), "tampered catalog must be rejected");
    }

    #[test]
    fn newer_revision_supersedes() {
        let a = Catalog { schema_version: 1, revision: 1, generated_at: chrono::Utc::now(), entries: vec![], source: "".into(), verified_signature: None };
        let b = Catalog { revision: 2, ..a.clone() };
        assert!(maybe_update_catalog(&a, &b));
        assert!(!maybe_update_catalog(&b, &a));
    }
}
